import sqlite3

CURRENCIES = [
    ('AED', 'د.إ', 'UAE Dirham (United Arab Emirates)', 'דירהם איחוד האמירויות (איחוד האמירויות הערביות)'),
    ('AFN', '؋', 'Afghan Afghani (Afghanistan)', 'אפגני (אפגניסטן)'),
    ('ALL', 'L', 'Albanian Lek (Albania)', 'לק אלבני (אלבניה)'),
    ('AMD', '֏', 'Armenian Dram (Armenia)', 'דראם ארמני (ארמניה)'),
    ('ANG', 'ƒ', 'Netherlands Antillean Guilder (Curaçao, Sint Maarten)', 'גילדר האנטילים ההולנדיים (קוראסאו, סנט מארטן)'),
    ('AOA', 'Kz', 'Angolan Kwanza (Angola)', 'קוואנזה אנגולי (אנגולה)'),
    ('ARS', '$', 'Argentine Peso (Argentina)', 'פזו ארגנטינאי (ארגנטינה)'),
    ('AUD', 'A$', 'Australian Dollar (Australia, Nauru, Tuvalu)', 'דולר אוסטרלי (אוסטרליה, נאורו, טובאלו)'),
    ('AWG', 'ƒ', 'Aruban Florin (Aruba)', 'פלורין של ארובה (ארובה)'),
    ('AZN', '₼', 'Azerbaijani Manat (Azerbaijan)', 'מאנאט אזרבייג\'ני (אזרבייג\'ן)'),
    ('BAM', 'KM', 'Bosnia-Herzegovina Convertible Mark (Bosnia and Herzegovina)', 'מארק סחיר (בוסניה והרצגובינה)'),
    ('BBD', '$', 'Barbadian Dollar (Barbados)', 'דולר ברבדוסי (ברבדוס)'),
    ('BDT', '৳', 'Bangladeshi Taka (Bangladesh)', 'טאקה בנגלדשי (בנגלדש)'),
    ('BGN', 'лв', 'Bulgarian Lev (Bulgaria)', 'לב בולגרי (בולגריה)'),
    ('BHD', '.د.ب', 'Bahraini Dinar (Bahrain)', 'דינר בחרייני (בחריין)'),
    ('BIF', 'FBu', 'Burundian Franc (Burundi)', 'פרנק בורונדי (בורונדי)'),
    ('BMD', '$', 'Bermudian Dollar (Bermuda)', 'דולר ברמודה (ברמודה)'),
    ('BND', '$', 'Brunei Dollar (Brunei)', 'דולר ברוניי (ברוניי)'),
    ('BOB', 'Bs.', 'Bolivian Boliviano (Bolivia)', 'בוליביאנו בוליביאני (בוליביה)'),
    ('BRL', 'R$', 'Brazilian Real (Brazil)', 'ריאל ברזילאי (ברזיל)'),
    ('BSD', '$', 'Bahamian Dollar (Bahamas)', 'דולר בהאמי (איי בהאמה)'),
    ('BTN', 'Nu.', 'Bhutanese Ngultrum (Bhutan)', 'נגולטרום בהוטני (בהוטן)'),
    ('BWP', 'P', 'Botswana Pula (Botswana)', 'פולה בוטסואני (בוטסואנה)'),
    ('BYN', 'Br', 'Belarusian Ruble (Belarus)', 'רובל בלארוסי (בלארוס)'),
    ('BZD', 'BZ$', 'Belize Dollar (Belize)', 'דולר בליזי (בליז)'),
    ('CAD', 'C$', 'Canadian Dollar (Canada)', 'דולר קנדי (קנדה)'),
    ('CDF', 'FC', 'Congolese Franc (Democratic Republic of the Congo)', 'פרנק קונגולזי (הרפובליקה הדמוקרטית של קונגו)'),
    ('CHF', 'Fr', 'Swiss Franc (Switzerland, Liechtenstein)', 'פרנק שוויצרי (שוויץ, ליכטנשטיין)'),
    ('CLP', '$', 'Chilean Peso (Chile)', 'פזו צ\'יליאני (צ\'ילה)'),
    ('CNY', '¥', 'Chinese Yuan (China)', 'יואן סיני (סין)'),
    ('COP', '$', 'Colombian Peso (Colombia)', 'פזו קולומביאני (קולומביה)'),
    ('CRC', '₡', 'Costa Rican Colón (Costa Rica)', 'קולון קוסטה ריקני (קוסטה ריקה)'),
    ('CUP', '₱', 'Cuban Peso (Cuba)', 'פזו קובני (קובה)'),
    ('CVE', '$', 'Cape Verdean Escudo (Cape Verde)', 'אסקודו כף ורדה (כף ורדה)'),
    ('CZK', 'Kč', 'Czech Koruna (Czech Republic)', 'קורונה צ\'כית (צ\'כיה)'),
    ('DJF', 'Fdj', 'Djiboutian Franc (Djibouti)', 'פרנק ג\'יבוטי (ג\'יבוטי)'),
    ('DKK', 'kr', 'Danish Krone (Denmark, Faroe Islands, Greenland)', 'כתר דני (דנמרק, איי פארו, גרינלנד)'),
    ('DOP', 'RD$', 'Dominican Peso (Dominican Republic)', 'פזו דומיניקני (הרפובליקה הדומיניקנית)'),
    ('DZD', 'د.ج', 'Algerian Dinar (Algeria)', 'דינר אלג\'ירי (אלג\'יריה)'),
    ('EGP', '£', 'Egyptian Pound (Egypt)', 'לירה מצרית (מצרים)'),
    ('ERN', 'Nfk', 'Eritrean Nakfa (Eritrea)', 'נאקפה אריתריאי (אריתריאה)'),
    ('ETB', 'Br', 'Ethiopian Birr (Ethiopia)', 'ביר אתיופי (אתיופיה)'),
    ('EUR', '€', 'Euro (European Union)', 'אירו (האיחוד האירופי)'),
    ('FJD', '$', 'Fijian Dollar (Fiji)', 'דולר פיג\'י (פיג\'י)'),
    ('FKP', '£', 'Falkland Islands Pound (Falkland Islands)', 'לירה של איי פוקלנד (איי פוקלנד)'),
    ('GBP', '£', 'British Pound (United Kingdom)', 'לירה שטרלינג (בריטניה)'),
    ('GEL', '₾', 'Georgian Lari (Georgia)', 'לארי גיאורגי (גיאורגיה)'),
    ('GHS', '₵', 'Ghanaian Cedi (Ghana)', 'סדי גנאי (גאנה)'),
    ('GIP', '£', 'Gibraltar Pound (Gibraltar)', 'לירה גיברלטרית (גיברלטר)'),
    ('GMD', 'D', 'Gambian Dalasi (Gambia)', 'דלאסי גמבי (גמביה)'),
    ('GNF', 'FG', 'Guinean Franc (Guinea)', 'פרנק גינאי (גינאה)'),
    ('GTQ', 'Q', 'Guatemalan Quetzal (Guatemala)', 'קצל גואטמלי (גואטמלה)'),
    ('GYD', '$', 'Guyanese Dollar (Guyana)', 'דולר גיאני (גיאנה)'),
    ('HKD', '$', 'Hong Kong Dollar (Hong Kong)', 'דולר הונג קונגי (הונג קונג)'),
    ('HNL', 'L', 'Honduran Lempira (Honduras)', 'למפירה הונדורסי (הונדורס)'),
    ('HTG', 'G', 'Haitian Gourde (Haiti)', 'גורד האיטי (האיטי)'),
    ('HUF', 'Ft', 'Hungarian Forint (Hungary)', 'פורינט הונגרי (הונגריה)'),
    ('IDR', 'Rp', 'Indonesian Rupiah (Indonesia)', 'רופיה אינדונזית (אינדונזיה)'),
    ('ILS', '₪', 'Israeli New Shekel (Israel)', 'שקל חדש (ישראל)'),
    ('INR', '₹', 'Indian Rupee (India, Bhutan, Nepal)', 'רופי הודי (הודו, בהוטן, נפאל)'),
    ('IQD', 'ع.د', 'Iraqi Dinar (Iraq)', 'דינר עיראקי (עיראק)'),
    ('IRR', '﷼', 'Iranian Rial (Iran)', 'ריאל איראני (איראן)'),
    ('ISK', 'kr', 'Icelandic Króna (Iceland)', 'קרונה איסלנדית (איסלנד)'),
    ('JMD', 'J$', 'Jamaican Dollar (Jamaica)', 'דולר ג\'מייקני (ג\'מייקה)'),
    ('JOD', 'د.ا', 'Jordanian Dinar (Jordan)', 'דינר ירדני (ירדן)'),
    ('JPY', '¥', 'Japanese Yen (Japan)', 'ין יפני (יפן)'),
    ('KES', 'KSh', 'Kenyan Shilling (Kenya)', 'שילינג קנייתי (קניה)'),
    ('KGS', 'лв', 'Kyrgyzstani Som (Kyrgyzstan)', 'סום קירגיזי (קירגיזסטן)'),
    ('KHR', '៛', 'Cambodian Riel (Cambodia)', 'ריל קמבודי (קמבודיה)'),
    ('KMF', 'CF', 'Comorian Franc (Comoros)', 'פרנק קומורואי (איי קומורו)'),
    ('KPW', '₩', 'North Korean Won (North Korea)', 'וון צפון קוריאני (צפון קוריאה)'),
    ('KRW', '₩', 'South Korean Won (South Korea)', 'וון דרום קוריאני (דרום קוריאה)'),
    ('KWD', 'د.ك', 'Kuwaiti Dinar (Kuwait)', 'דינר כוויתי (כווית)'),
    ('KYD', '$', 'Cayman Islands Dollar (Cayman Islands)', 'דולר איי קיימן (איי קיימן)'),
    ('KZT', '₸', 'Kazakhstani Tenge (Kazakhstan)', 'טנגה קזחי (קזחסטן)'),
    ('LAK', '₭', 'Lao Kip (Laos)', 'קיפ לאי (לאוס)'),
    ('LBP', '£', 'Lebanese Pound (Lebanon)', 'לירה לבנונית (לבנון)'),
    ('LKR', '₨', 'Sri Lankan Rupee (Sri Lanka)', 'רופי סרי לנקי (סרי לנקה)'),
    ('LRD', '$', 'Liberian Dollar (Liberia)', 'דולר ליברי (ליבריה)'),
    ('LSL', 'L', 'Lesotho Loti (Lesotho)', 'לוטי לסותי (לסוטו)'),
    ('LYD', 'ل.د', 'Libyan Dinar (Libya)', 'דינר לובי (לוב)'),
    ('MAD', 'د.م.', 'Moroccan Dirham (Morocco)', 'דירהם מרוקאי (מרוקו)'),
    ('MDL', 'L', 'Moldovan Leu (Moldova)', 'לאו מולדובני (מולדובה)'),
    ('MGA', 'Ar', 'Malagasy Ariary (Madagascar)', 'אריארי מלגשי (מדגסקר)'),
    ('MKD', 'ден', 'Macedonian Denar (North Macedonia)', 'דינר מקדוני (מקדוניה הצפונית)'),
    ('MMK', 'K', 'Myanmar Kyat (Myanmar)', 'קיאט מיאנמרי (מיאנמר)'),
    ('MNT', '₮', 'Mongolian Tögrög (Mongolia)', 'טוגרוג מונגולי (מונגוליה)'),
    ('MOP', 'P', 'Macanese Pataca (Macau)', 'פטקה של מקאו (מקאו)'),
    ('MRU', 'UM', 'Mauritanian Ouguiya (Mauritania)', 'אוגויה מוריטני (מוריטניה)'),
    ('MUR', '₨', 'Mauritian Rupee (Mauritius)', 'רופי מאוריציני (מאוריציוס)'),
    ('MVR', 'MVR', 'Maldivian Rufiyaa (Maldives)', 'רופיה מלדיבית (האיים המלדיביים)'),
    ('MWK', 'MK', 'Malawian Kwacha (Malawi)', 'קוואצ\'ה מלאווי (מלאווי)'),
    ('MXN', '$', 'Mexican Peso (Mexico)', 'פזו מקסיקני (מקסיקו)'),
    ('MYR', 'RM', 'Malaysian Ringgit (Malaysia)', 'רינגיט מלזי (מלזיה)'),
    ('MZN', 'MT', 'Mozambican Metical (Mozambique)', 'מטיקל מוזמביקי (מוזמביק)'),
    ('NAD', '$', 'Namibian Dollar (Namibia)', 'דולר נמיבי (נמיביה)'),
    ('NGN', '₦', 'Nigerian Naira (Nigeria)', 'נאירה ניגרי (ניגריה)'),
    ('NIO', 'C$', 'Nicaraguan Córdoba (Nicaragua)', 'קורדובה ניקרגואי (ניקרגואה)'),
    ('NOK', 'kr', 'Norwegian Krone (Norway)', 'קרונה נורווגית (נורווגיה)'),
    ('NPR', '₨', 'Nepalese Rupee (Nepal)', 'רופי נפאלי (נפאל)'),
    ('NZD', '$', 'New Zealand Dollar (New Zealand)', 'דולר ניו זילנדי (ניו זילנד)'),
    ('OMR', 'ر.ع.', 'Omani Rial (Oman)', 'ריאל עומאני (עומאן)'),
    ('PAB', 'B/.', 'Panamanian Balboa (Panama)', 'בלבואה פנמי (פנמה)'),
    ('PEN', 'S/', 'Peruvian Sol (Peru)', 'סול פרואני (פרו)'),
    ('PGK', 'K', 'Papua New Guinean Kina (Papua New Guinea)', 'קינה של פפואה גינאה החדשה (פפואה גינאה החדשה)'),
    ('PHP', '₱', 'Philippine Peso (Philippines)', 'פזו פיליפיני (הפיליפינים)'),
    ('PKR', '₨', 'Pakistani Rupee (Pakistan)', 'רופי פקיסטני (פקיסטן)'),
    ('PLN', 'zł', 'Polish Złoty (Poland)', 'זלוטי פולני (פולין)'),
    ('PYG', '₲', 'Paraguayan Guaraní (Paraguay)', 'גווארני פרגוואי (פרגוואי)'),
    ('QAR', 'ر.ق', 'Qatari Riyal (Qatar)', 'ריאל קטרי (קטר)'),
    ('RON', 'lei', 'Romanian Leu (Romania)', 'לאו רומני (רומניה)'),
    ('RSD', 'дин.', 'Serbian Dinar (Serbia)', 'דינר סרבי (סרביה)'),
    ('RUB', '₽', 'Russian Ruble (Russia)', 'רובל רוסי (רוסיה)'),
    ('RWF', 'FRw', 'Rwandan Franc (Rwanda)', 'פרנק רואנדי (רואנדה)'),
    ('SAR', 'ر.س', 'Saudi Riyal (Saudi Arabia)', 'ריאל סעודי (ערב הסעודית)'),
    ('SBD', '$', 'Solomon Islands Dollar (Solomon Islands)', 'דולר איי שלמה (איי שלמה)'),
    ('SCR', '₨', 'Seychellois Rupee (Seychelles)', 'רופי סיישלי (סיישל)'),
    ('SDG', 'ج.س.', 'Sudanese Pound (Sudan)', 'לירה סודאנית (סודאן)'),
    ('SEK', 'kr', 'Swedish Krona (Sweden)', 'קרונה שוודית (שוודיה)'),
    ('SGD', '$', 'Singapore Dollar (Singapore)', 'דולר סינגפורי (סינגפור)'),
    ('SHP', '£', 'Saint Helena Pound (Saint Helena)', 'לירה של סנט הלנה (סנט הלנה)'),
    ('SLL', 'Le', 'Sierra Leonean Leone (Sierra Leone)', 'ליאון סיירה לאוני (סיירה לאון)'),
    ('SOS', 'S', 'Somali Shilling (Somalia)', 'שילינג סומלי (סומליה)'),
    ('SRD', '$', 'Surinamese Dollar (Suriname)', 'דולר סורינאמי (סורינאם)'),
    ('SSP', '£', 'South Sudanese Pound (South Sudan)', 'לירה דרום סודאנית (דרום סודאן)'),
    ('STN', 'Db', 'São Tomé and Príncipe Dobra (São Tomé and Príncipe)', 'דוברה של סאו טומה ופרינסיפה (סאו טומה ופרינסיפה)'),
    ('SYP', '£', 'Syrian Pound (Syria)', 'לירה סורית (סוריה)'),
    ('SZL', 'L', 'Swazi Lilangeni (Eswatini)', 'לילנגני סווזי (אסוואטיני)'),
    ('THB', '฿', 'Thai Baht (Thailand)', 'באט תאילנדי (תאילנד)'),
    ('TJS', 'SM', 'Tajikistani Somoni (Tajikistan)', 'סומוני טג\'יקי (טג\'יקיסטן)'),
    ('TMT', 'T', 'Turkmenistan Manat (Turkmenistan)', 'מאנאט טורקמני (טורקמניסטן)'),
    ('TND', 'د.ت', 'Tunisian Dinar (Tunisia)', 'דינר תוניסאי (תוניסיה)'),
    ('TOP', 'T$', 'Tongan Paʻanga (Tonga)', 'פאנגה טונגאי (טונגה)'),
    ('TRY', '₺', 'Turkish Lira (Turkey)', 'לירה טורקית (טורקיה)'),
    ('TTD', 'TT$', 'Trinidad and Tobago Dollar (Trinidad and Tobago)', 'דולר של טרינידד וטובגו (טרינידד וטובגו)'),
    ('TWD', 'NT$', 'New Taiwan Dollar (Taiwan)', 'דולר טאיוואני חדש (טאיוואן)'),
    ('TZS', 'TSh', 'Tanzanian Shilling (Tanzania)', 'שילינג טנזני (טנזניה)'),
    ('UAH', '₴', 'Ukrainian Hryvnia (Ukraine)', 'הריבניה אוקראינית (אוקראינה)'),
    ('UGX', 'USh', 'Ugandan Shilling (Uganda)', 'שילינג אוגנדי (אוגנדה)'),
    ('USD', '$', 'US Dollar (United States)', 'דולר ארה"ב (ארצות הברית)'),
    ('UYU', '$U', 'Uruguayan Peso (Uruguay)', 'פזו אורוגוואי (אורוגוואי)'),
    ('UZS', 'so\'m', 'Uzbekistani Soʻm (Uzbekistan)', 'סום אוזבקי (אוזבקיסטן)'),
    ('VES', 'Bs.S.', 'Venezuelan Bolívar Soberano (Venezuela)', 'בוליבר ונצואלי (ונצואלה)'),
    ('VND', '₫', 'Vietnamese Đồng (Vietnam)', 'דונג וייטנאמי (וייטנאם)'),
    ('VUV', 'VT', 'Vanuatu Vatu (Vanuatu)', 'ואטו של ונואטו (ונואטו)'),
    ('WST', 'WS$', 'Samoan Tālā (Samoa)', 'טאלה סמואי (סמואה)'),
    ('XAF', 'FCFA', 'Central African CFA Franc (CEMAC)', 'פרנק CFA מרכז אפריקאי (מדינות CEMAC)'),
    ('XCD', '$', 'East Caribbean Dollar (OECS)', 'דולר מזרח קריבי (ארגון מדינות מזרח הקריביים)'),
    ('XOF', 'CFA', 'West African CFA Franc (UEMOA)', 'פרנק CFA מערב אפריקאי (מדינות UEMOA)'),
    ('XPF', '₣', 'CFP Franc (French Polynesia, New Caledonia)', 'פרנק פסיפי (פולינזיה הצרפתית, קלדוניה החדשה)'),
    ('YER', '﷼', 'Yemeni Rial (Yemen)', 'ריאל תימני (תימן)'),
    ('ZAR', 'R', 'South African Rand (South Africa)', 'ראנד דרום אפריקאי (דרום אפריקה)'),
    ('ZMW', 'ZK', 'Zambian Kwacha (Zambia)', 'קוואצ\'ה זמבי (זמביה)'),
    ('ZWL', '$', 'Zimbabwean Dollar (Zimbabwe)', 'דולר זימבבואי (זימבבואה)')
]

def update_db(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute('''CREATE TABLE IF NOT EXISTS Currencies (
        code TEXT PRIMARY KEY,
        symbol TEXT NOT NULL,
        name_en TEXT NOT NULL,
        name_he TEXT NOT NULL
    )''')
    for curr in CURRENCIES:
        cursor.execute('''
            INSERT INTO Currencies (code, symbol, name_en, name_he)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(code) DO UPDATE SET
                symbol=excluded.symbol,
                name_en=excluded.name_en,
                name_he=excluded.name_he
        ''', curr)
    conn.commit()
    conn.close()
    print("Currencies updated successfully in", db_path)

if __name__ == "__main__":
    update_db("master_splitter.db")
